### ISSUE TITLE
library fails to find ✌

### ISSUE THREAD

**Issue by Zamiell** [tmdvs/Go-Emoji-Utils#10]
e.g.

```
package main

import (
        "fmt"
        emoji "github.com/tmdvs/Go-Emoji-Utils"
)

func main() {
        username := "✌"
        if searchResults := emoji.FindAll(username); len(searchResults) > 0 {
                fmt.Println("found an emoji in the username")
        } else {
                fmt.Println("no emojis found in the username")
        }
}
```

**Comment by tmdvs** [comment]
I did some testing around this. While it can't detect the `✌` in your example, it can detect it if inserted via the macOS emoji picker… 

I'll do some more investigation

**Comment by WisperDin** [comment]
In this example, the value he test is ```✌``` (270C), but not 270C-FE0F in `emoji.json`. So it can't be found.

**Comment by Zamiell** [comment]
can you link the commit that this was completed in?

**Comment by tmdvs** [comment]
@Zamiell I wrote a specific test for this in v1.2.0 and the ✌️ emoji passes:

```go
func TestPeaceSign(t *testing.T) {
	str := "✌️" // this is the v/peace sign emoji
	matches := emoji.FindAll(str)
	assert.Equal(t, matches[0].Match.(emoji.Emoji).Descriptor, "Victory Hand", "The emoji should be a Victory Hand")
}
```

> [!IMPORTANT]  
> Please note that your original example is the [unicode victory hand](https://www.compart.com/en/unicode/U+270C) and not the [victory hand emoji](https://emojipedia.org/victory-hand). This package is for emoji specifically and not unicode.
