### ISSUE TITLE
FindAll method returns wrong results for some emojis (e.g. 👨‍👩‍👦‍👦))

### ISSUE THREAD

**Issue by sophiekeum** [tmdvs/Go-Emoji-Utils#12]
![스크린샷 2021-02-19 오전 10 22 46](https://user-images.githubusercontent.com/77473044/108444058-3d5eff80-729d-11eb-9292-68a35aa86e1c.png)

For this, findAll method detects two emojis and it happens for other emojis with 2 sons. 

![스크린샷 2021-02-19 오전 10 22 59](https://user-images.githubusercontent.com/77473044/108444067-4059f000-729d-11eb-87ed-3b12543680e3.png)

**Comment by YamiOdymel** [comment]
The family emoji `👨‍👩‍👦‍👦` is an emoji collection, it combines the emojis with emoji connectors (`200D`).

A workaround hack is to ignore the unicode if the last unicode is an emoji connector.

```diff
// If this index has been flaged as a modifier we do
// not want to process it again
if detectedModifiers[index] {
	continue
}

+ if index-1 >= 0 && utils.RunesToHexKey([]rune{runes[index-1]}) == "200D" {
+	continue
+ }
```

The line of code can be found in `search.go#L68`

https://github.com/tmdvs/Go-Emoji-Utils/blob/89e1e92ad3b5aabd3bab2abff4c5758844df0156/search.go#L68-L73
