### ISSUE TITLE
two bugs for ReplaceAll

### ISSUE THREAD

**Issue by tomjamescn** [tmdvs/Go-Emoji-Utils#2]
I have use this lib in my project, found two bugs:

1. panic for continus emoji chars such as "abc🙏🙏🙏🙏🙏"
2. will replace multi blank chars to only one such as "abc   d"

**Comment by emauro** [comment]
Perhaps it is related with my report (see #3).

**Comment by tmdvs** [comment]
This looks to have been fixed by a recent PR merge. I've just released [v1.0.1](https://github.com/tmdvs/Go-Emoji-Utils/releases/tag/v1.0.1), hopefully your issue is resolved.
