### ISSUE TITLE
vendoring does not work

### ISSUE THREAD

**Issue by Gys** [tmdvs/Go-Emoji-Utils#7]
I have a /vendor directory in a project and wanted to use this library. However, I got some strange problems.

Initially the /data/emoji.json was not copied as part of the library. I use 'govendor' to manage the vendor folder in many projects, but in this case only part of the library was copied. Very strange. I had to copy 'data/emoji.json' by hand to add it.

Even after I added the emoji.json the application paniced when deployed to Heroku: file not found. Locally it ran fine. So maybe remotely the path is a little different then expected.

**Comment by biter777** [comment]
You can use a fork, where it is solved.
https://github.com/biter777/Go-Emoji-Utils

**Comment by ALTELMA** [comment]
I try to install your fork with glide, but I got

`Failed to checkout packages: Cannot detect VCS`

**Comment by ALTELMA** [comment]
When we build it could not find data/emoji.json. Please fix this problem.

**Comment by tmdvs** [comment]
Resolved through merging https://github.com/tmdvs/Go-Emoji-Utils/pull/8
