### ISSUE TITLE
Add Emoji's short codes to Emoji type

### ISSUE THREAD

**Issue by leobragaz** [tmdvs/Go-Emoji-Utils#9]
During those days is a common practice in social networks to use and support emoji's [short codes.](https://www.webfx.com/tools/emoji-cheat-sheet/)
I would suggest to add them to the type Emoji and add functions that let searching emoji using shortcodes.
So for example `Emoji` type should become:
```golang
type Emoji struct {
	Key        string `json:"key"`
	Value      string `json:"value"`
	Descriptor string `json:"descriptor"`
        ShortCode  string `json:"short_code"`
}
```
and an emoji should look like this:
```
Emoji{ Key:"1F437", Value:"🐷", Descriptor: "pig", ShortCode: ":pig:" }
```
Let me know what do you think, I can also make a PR for this.

**Comment by tmdvs** [comment]
This could be really useful! Feel free to submit a PR 👍
